export const productList = [
  { id: 1, name: '1', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto1' },
  { id: 2, name: '2', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 3, name: '3', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 4, name: '4', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 5, name: '5', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 6, name: '6', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 7, name: '7', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 8, name: '8', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 9, name: '9', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 10, name: '10', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 11, name: '11', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 12, name: '12', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 13, name: '13', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
  { id: 14, name: '14', imageUrl: 'produto.jpg', productUrl: 'https://exemplo.com/produto2' },
];
